# Generated by Django 5.2.6 on 2025-09-28 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bank_accountid_profile_bank_customerid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_accountId',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_customerId',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField()),
                ('merchant_id', models.CharField()),
                ('purchase_date', models.DateField()),
                ('amount', models.CharField()),
                ('description', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchase_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
