# Generated by Django 5.2.6 on 2025-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_itempurchasehistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
